name: AiraaCheisyaa CRD (Overpowered - Manual Input)

on:
  workflow_dispatch:
    inputs:
      crd_full_command:
        description: 'Salin dan tempel SELURUH perintah dari halaman CRD Headless (CMD atau PowerShell)'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: ☁️ Preparing Environment
        run: |
          Write-Host "📦 Menginstal Chrome Remote Desktop..."
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "crd.msi"
          Start-Process msiexec.exe -Wait -ArgumentList '/i crd.msi /qn'
          Write-Host "✅ CRD Terinstal."
        shell: pwsh

      - name: 🚀 Applying Overpowered Tweaks
        run: |
          Write-Host "🚀 Menerapkan optimasi sistem yang agresif..."
          
          # 1. Power Plan: Ultimate Performance (jika ada) atau High Performance
          powercfg /s SCHEME_MIN
          powercfg -setacvalueindex SCHEME_MIN SUB_PROCESSOR PROCTHROTTLEMAX 100
          powercfg -setacvalueindex SCHEME_MIN SUB_PROCESSOR PROCTHROTTLEMIN 100
          powercfg -setactive SCHEME_MIN
          Write-Host "⚡ Power Plan diatur ke High Performance."

          # 2. Disable Windows Defender (lebih agresif)
          Set-MpPreference -DisableRealtimeMonitoring $true -Force
          Set-MpPreference -DisableBehaviorMonitoring $true -Force
          Set-MpPreference -DisableBlockAtFirstSeen $true -Force
          Set-MpPreference -DisableIOAVProtection $true -Force
          Set-MpPreference -DisableScriptScanning $true -Force
          Set-MpPreference -EnableControlledFolderAccess Disabled -Force
          Write-Host "🛡️ Windows Defender dinonaktifkan sepenuhnya."

          # 3. Disable Services (lebih banyak service)
          $servicesToDisable = @("wuauserv", "WSearch", "SysMain", "BITS", "DoSvc")
          foreach ($service in $servicesToDisable) {
            Stop-Service -Name $service -Force -ErrorAction SilentlyContinue
            Set-Service -Name $service -StartupType Disabled -ErrorAction SilentlyContinue
          }
          Write-Host "⚙️ Service yang tidak perlu telah dinonaktifkan."

          # 4. Optimize Visual Effects for Performance
          Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects' -Name 'VisualFxSetting' -Value 2
          $visualEffectsPath = "HKCU:\Control Panel\Desktop"
          Set-ItemProperty -Path $visualEffectsPath -Name 'DragFullWindows' -Value '0'
          Set-ItemProperty -Path $visualEffectsPath -Name 'FontSmoothing' -Value '0'
          Set-ItemProperty -Path $visualEffectsPath -Name 'UserPreferencesMask' -Value ([byte[]](0x90,0x12,0x03,0x80,0x10,0x00,0x00,0x00))
          Write-Host "🎨 Efek visual telah dioptimalkan untuk performa."

          # 5. Network & TCP Optimizations
          netsh int tcp set global autotuninglevel=highlyrestricted
          netsh int tcp set global chimney=disabled
          netsh int tcp set global rss=disabled
          netsh int tcp set global ecncapability=disabled
          Write-Host "🌐 Jaringan dioptimalkan untuk latensi rendah."
          
          # 6. Disable Windows Firewall (WARNING: Use with caution)
          netsh advfirewall set allprofiles state off
          Write-Host "🔥 Windows Firewall dinonaktifkan (Performa Maksimal)."
          
          Write-Host "✅ Semua tweak performa 'Over Power' telah diterapkan."
        shell: pwsh

      - name: 🔗 Connecting to Chrome Remote Desktop
        run: |
          $FullCommand = '${{ github.event.inputs.crd_full_command }}'
          
          # Ekstraksi AuthCode/Token dari perintah yang di-paste pengguna
          $AuthCode = ''
          if ($FullCommand -match '--code="(.+?)"') {
              $AuthCode = "--code=`"$($matches[1])`" --redirect-url=`"https://remotedesktop.google.com/_/oauthredirect`""
          } elseif ($FullCommand -match '--token="(.+?)"') {
              $AuthCode = "--token=`"$($matches[1])`""
          } else {
              Write-Error "❌ Auth Code atau Token tidak ditemukan dalam perintah yang Anda berikan."
              exit 1
          }

          $HostName = "gh-runner-${{ github.run_id }}"
          $PIN = "123456" # PIN Statis dikembalikan
          
          # Menjalankan CRD Host menggunakan perintah yang diekstrak
          $ArgumentList = "$AuthCode --name=`"$HostName`" -pin=`"$PIN`""
          Start-Process -FilePath "C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" -ArgumentList $ArgumentList
          
          # Loop pengecekan dan peningkatkan prioritas proses (lebih stabil)
          Write-Host "⏳ Menunggu proses CRD Host aktif..."
          $crdProcess = $null
          $timeout = 15 # detik
          $stopwatch = [System.Diagnostics.Stopwatch]::StartNew()
          
          while ($crdProcess -eq $null -and $stopwatch.Elapsed.TotalSeconds -lt $timeout) {
            $crdProcess = Get-Process -Name "remoting_host" -ErrorAction SilentlyContinue
            Start-Sleep -Seconds 1
          }
          $stopwatch.Stop()
          
          if ($crdProcess) {
            $crdProcess.PriorityClass = [System.Diagnostics.ProcessPriorityClass]::High
            Write-Host ("🔥 Prioritas CRD Host PID: " + $crdProcess.Id + " telah ditingkatkan ke HIGH.")
          } else {
            Write-Warning "⚠️ Proses CRD tidak ditemukan setelah $timeout detik."
          }

          Write-Host "========================= RDP INFO ========================="
          Write-Host "✅ Host Name  : $HostName"
          Write-Host "✅ PIN        : $PIN  (PIN Statis)"
          Write-Host "✅ User       : runneradmin"
          Write-Host "✅ Password   : (Gunakan password default dari GitHub)"
          Write-Host "============================================================"
          Write-Host "💡 Sesi RDP aktif. Workflow akan terus berjalan..."
        shell: pwsh

      - name: 💻 Keep Runner Alive
        run: Start-Sleep -Seconds 21000 # Sedikit di bawah 6 jam untuk keamanan
        shell: pwsh
        
